package edu.tum.cup2.test;

import static edu.tum.cup2.test.SpecCalc4.NonTerminals.*;
import static edu.tum.cup2.test.SpecCalc4.Terminals.*;

import edu.tum.cup2.grammar.*;
import edu.tum.cup2.scanner.*;


/**
 * This class is a scanner for the {@link SpecCalc4} grammar.
 * It was generated by JFlex, using the file SpecCalc4.jflex.
 *
 * @author Andreas Wenger
 */
%%
%class SpecCalc4Scanner
%implements Scanner
%unicode
%line
%column

%function readNextTerminal
%type ScannerToken

%{

	private ScannerToken<Object> token(Terminal terminal)
	{
		return new ScannerToken<Object>(terminal);
	}

%}
%eofval{
    return token(SpecialTerminals.EndOfInputStream);
%eofval}
 
%%
"+" { return token(PLUS); }
"-" { return token(MINUS); }
"*" { return token(MULT); }
"/" { return token(DIV); }
"(" { return token(LBR); }
")" { return token(RBR); }
[0-9]+ { return new ScannerToken<Object>(NUMBER, new Integer(yytext())); }
[ \t\r\n\f] { /* ignore white space. */ }
. { System.err.println("Illegal character: "+yytext()); }
