package edu.tum.cup2.spec;

import static edu.tum.cup2.spec.SampleSpec.NonTerminals.*;
import static edu.tum.cup2.spec.SampleSpec.Terminals.*;

import edu.tum.cup2.grammar.*;
import edu.tum.cup2.scanner.*;


/**
 * This class is a scanner for the {@link SampleSpec} grammar.
 * It was generated by JFlex, using the file SampleSpecScanner.jflex.
 *
 * @author Andreas Wenger
 */
%%
%class SampleSpecScanner
%implements Scanner
%unicode
%line
%column

%function readNextTerminal
%type ScannerToken

%{

	private ScannerToken<Object> token(Terminal terminal)
	{
		return new ScannerToken<Object>(terminal);
	}

%}
%eofval{
    return token(SpecialTerminals.EndOfInputStream);
%eofval}
 
%%
";" { return token(SEMI); }
"+" { return token(PLUS); }
"*" { return token(TIMES); }
"(" { return token(LPAREN); }
")" { return token(RPAREN); }
[0-9]+ { return new ScannerToken<Object>(NUMBER, new Integer(yytext())); }
[ \t\r\n\f] { /* ignore white space. */ }
. { System.err.println("Illegal character: "+yytext()); }
